# Site wide configuration

title:            Huan Truong's Pensieve
locale:           en_US
domain:           tnhh.net
url:              https://www.tnhh.net
ampurl:           https://www-tnhh-net.cdn.ampproject.org/c/www.tnhh.net
permaurl:         https://www.tnhh.net
logo:             /images/logo.png
logo_h:           60
logo_w:           151
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Jekyll configuration

permalink:   /posts/:title.html
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-feed
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

collections:
  my_categories:
    output: true
    permalink: /topic/:name/

defaults:
-
  scope:
    path: ""
    type: pages
  values:
    permalink: /:path/:basename:output_ext
    layout: page
-
  scope:
    path: ""
    type: posts
  values:
    layout: post
-
  scope:
    path: ""
    type: my_categories
  values:
    layout: blog_by_category

# Site owner
owner:
  name: "Huan Truong"
  avatar: /images/bio-photo.jpg
  bio: "Hacks and stuff"
  email: 
  disqus-shortname: tnhh
  twitter: huant
  facebook: #username
  google:
    plus: #username
    analytics: #UA-89021900-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: htruong
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: huantruong 
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
